src/csis_coursemanager/Controllers/CoursesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using csis_coursemanager.Models;
using Microsoft.AspNet.Authorization;
using System;

namespace csis_coursemanager.Controllers
{
    public class CoursesController : Controller
    {
        private ApplicationDbContext _context;

        public CoursesController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Courses
        public IActionResult Index(string searchString)
        {
            var courses = from s in _context.Course
                            select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                courses = courses.Where(s => s.CourseTitle.Contains(searchString));
            }
            var applicationDbContext = _context.Course.Include(c => c.CourseAssistant);
            return View(courses.ToList());
        }

        // GET: Courses/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Course course = _context.Course.Single(m => m.CourseID == id);
            if (course == null)
            {
                return HttpNotFound();
            }

            return View(course);
        }

        // GET: Courses/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CourseAssistantID"] = new SelectList(_context.CourseAssistant, "CourseAssistantID", "CourseAssistant");
            return View();
        }

        // POST: Courses/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Course.Add(course);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["CourseAssistantID"] = new SelectList(_context.CourseAssistant, "CourseAssistantID", "CourseAssistant", course.CourseAssistantID);
            return View(course);
        }

        // GET: Courses/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Course course = _context.Course.Single(m => m.CourseID == id);
            if (course == null)
            {
                return HttpNotFound();
            }
            ViewData["CourseAssistantID"] = new SelectList(_context.CourseAssistant, "CourseAssistantID", "CourseAssistant", course.CourseAssistantID);
            return View(course);
        }

        // POST: Courses/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Course course)
        {
            if (ModelState.IsValid)
            {
                _context.Update(course);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["CourseAssistantID"] = new SelectList(_context.CourseAssistant, "CourseAssistantID", "CourseAssistant", course.CourseAssistantID);
            return View(course);
        }

        // GET: Courses/Delete/5
        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Course course = _context.Course.Single(m => m.CourseID == id);
            if (course == null)
            {
                return HttpNotFound();
            }

            return View(course);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(int id)
        {
            Course course = _context.Course.Single(m => m.CourseID == id);
            _context.Course.Remove(course);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/csis_coursemanager/Controllers/FacultiesController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using csis_coursemanager.Models;
using System;
using Microsoft.AspNet.Authorization;

namespace csis_coursemanager.Controllers
{
    public class FacultiesController : Controller
    {
        private ApplicationDbContext _context;

        public FacultiesController(ApplicationDbContext context)
        {
            _context = context;    
        }
        
        // GET: Faculties
        public IActionResult Index(string sortOrder, string searchString)
        {
            //var applicationDbContext = _context.Faculty.Include(f => f.Course);
            //return View(applicationDbContext.ToList());
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";           

            ViewBag.CurrentFilter = searchString;
            var faculties = from s in _context.Faculty
                            select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                faculties = faculties.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    faculties = faculties.OrderByDescending(s => s.Name);
                    break;
                //case "Date":
                //    students = students.OrderBy(s => s.EnrollmentDate);
                //    break;
                //case "date_desc":
                //    students = students.OrderByDescending(s => s.EnrollmentDate);
                //    break;
                default:
                    faculties = faculties.OrderBy(s => s.Name);
                    break;
            }
            return View(faculties.ToList());
        }

        // GET: Faculties/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculty.Single(m => m.FacultyID == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            return View(faculty);
        }

        // GET: Faculties/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course");
            return View();
        }

        // POST: Faculties/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Faculty.Add(faculty);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course", faculty.CourseID);
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculty.Single(m => m.FacultyID == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course", faculty.CourseID);
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Update(faculty);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course", faculty.CourseID);
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        [ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Faculty faculty = _context.Faculty.Single(m => m.FacultyID == id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteConfirmed(int id)
        {
            Faculty faculty = _context.Faculty.Single(m => m.FacultyID == id);
            _context.Faculty.Remove(faculty);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/csis_coursemanager/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;

namespace csis_coursemanager.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            //ViewData["Message"] = "";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "CSIS Course Manager.";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

src/csis_coursemanager/Controllers/JobsController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using csis_coursemanager.Models;
using Microsoft.AspNet.Authorization;

namespace csis_coursemanager.Controllers
{
    public class JobsController : Controller
    {
        private ApplicationDbContext _context;

        public JobsController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Jobs
        public IActionResult Index()
        {
            var applicationDbContext = _context.Job.Include(j => j.Course);
            return View(applicationDbContext.ToList());
        }

        // GET: Jobs/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Job job = _context.Job.Single(m => m.JobID == id);
            if (job == null)
            {
                return HttpNotFound();
            }

            return View(job);
        }

        // GET: Jobs/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course");
            return View();
        }

        // POST: Jobs/Create
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Job.Add(job);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course", job.CourseID);
            return View(job);
        }

        // GET: Jobs/Edit/5
        [Authorize(Roles = "Admin")]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Job job = _context.Job.Single(m => m.JobID == id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course", job.CourseID);
            return View(job);
        }

        // POST: Jobs/Edit/5
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Job job)
        {
            if (ModelState.IsValid)
            {
                _context.Update(job);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewData["CourseID"] = new SelectList(_context.Course, "CourseID", "Course", job.CourseID);
            return View(job);
        }

        // GET: Jobs/Delete/5
        [Authorize(Roles = "Admin")]
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Job job = _context.Job.Single(m => m.JobID == id);
            if (job == null)
            {
                return HttpNotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Job job = _context.Job.Single(m => m.JobID == id);
            _context.Job.Remove(job);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/csis_coursemanager/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>
<div>
    <div style="float:left; width:20%;">
        <img src="http://www.glewisassociates.com/wp-content/uploads/2015/10/Contact-Us.jpg" width="600" style="margin-top:20px;border:4px solid #ebebeb;" />
    </div>
    <div style="float:right; width:40%; margin-left:10px;">
        <div class="col-md-9">
            <div class="contact-form">
                <h4>Contact Info</h4>
                <address>
                    <strong>CSIS Course Manager.</strong><br>
                    800 University Dr, <br>
                    Maryville, MO, 64468<br>
                    <abbr title="Phone">P:</abbr> (660) 456-7890
                </address>
                <form action="MAILTO:csiscoursemanager@gmail.com" method="post" enctype="text/plain">
                    <div class="form-group">
                        <input type="text" name="name" class="form-control" placeholder="Name" required>
                    </div>
                    <div class="form-group">
                        <input type="email" name="email" class="form-control" placeholder="Email" required>
                    </div>
                    <div class="form-group">
                        <input type="text" name="subject" class="form-control" placeholder="Subject" required>
                    </div>
                    <div class="form-group">
                        <textarea name="message" class="form-control" rows="8" placeholder="Message" required></textarea>
                    </div>
                    <button type="submit"> Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script src='https://maps.googleapis.com/maps/api/js?v=3.exp'></script><div style='overflow:hidden;height:440px;width:900px;'>
    <div id='gmap_canvas' style='height:440px;width:700px;'></div><div><small><a href="http://embedgooglemaps.com">									embed google maps							</a></small></div><div><small><a href="http://www.buywebtrafficexperts.com">buy targeted traffic</a></small></div>
    <style>
        #gmap_canvas img {
            max-width: none !important;
            background: none !important;
        }
    </style>
</div>
<script type='text/javascript'>function init_map() { var myOptions = { zoom: 10, center: new google.maps.LatLng(51.5073509, -0.12775829999998223), mapTypeId: google.maps.MapTypeId.ROADMAP }; map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions); marker = new google.maps.Marker({ map: map, position: new google.maps.LatLng(51.5073509, -0.12775829999998223) }); infowindow = new google.maps.InfoWindow({ content: '<strong>ContactUS</strong><br>NorthWest Missouri State University<br>' }); google.maps.event.addListener(marker, 'click', function () { infowindow.open(map, marker); }); infowindow.open(map, marker); } google.maps.event.addDomListener(window, 'load', init_map);</script>



<div class="clearfix"></div>

src/csis_coursemanager/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <section id="intro" class="intro">
                <div class="slogan">
                    <h2 class="bounceInDown">WELCOME TO <span class="text_color">CSIS Course Manager</span> </h2>
                    <h4>
                        This app would help students and faculty to keep track of all the course details like<br /> syllabus, faculty members, teaching assistants, duration, credits, job postings
                    </h4>
                </div>
                <div class="page-scroll">
                    <a href="#service" class="btn btn-circle">
                        <i class="fa fa-angle-double-down animated"></i>
                    </a>
                </div>
            </section>
        </div>
        <div class="item">
            <img src="~/images/carousel1.jpg" alt="CSIS Course Manager" class="img-responsive" />
        </div>
        <div class="item">
            <img src="~/images/carousel2.jpg" alt="CSIS Course Manager" class="img-responsive" />
            
        </div>
        <div class="item">
            <img src="~/images/carousel3.jpg" alt="CSIS Course Manager" class="img-responsive" />
            
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row" id="sections">
    <a asp-controller="Courses" asp-action="Index">
        <div class="col-xs-6 col-sm-3 col-md-3">
            <div class="team boxed-grey">
                <div class="inner">
                    <h5>Courses</h5>
                    <div class="avatar"><img src="~/images/c6.jpg" alt="" class="img-responsive img-circle"></div>
                </div>
            </div>
        </div>
    </a>
    <a asp-controller="Faculties" asp-action="Index">
        <div class="col-xs-6 col-sm-3 col-md-3">
            <div class="team boxed-grey">
                <div class="inner">
                    <h5>Faculty</h5>
                    <div class="avatar"><img src="~/images/faculty.jpg" alt="" class="img-responsive img-circle"></div>
                </div>
            </div>
        </div>
    </a>
    <a asp-controller="Jobs" asp-action="Index">
        <div class="col-xs-6 col-sm-3 col-md-3">
            <div class="team boxed-grey">
                <div class="inner">
                    <h5>Jobs</h5>
                    <div class="avatar"><img src="~/images/jobs.jpg" alt="" class="img-responsive img-circle"></div>
                </div>
            </div>
        </div>
    </a>
    <a asp-controller="Jobs" asp-action="Index">
        <div class="col-xs-6 col-sm-3 col-md-3">
            <div class="team boxed-grey">
                <div class="inner">
                    <h5>User Reviews</h5>
                    <div class="avatar"><img src="~/images/reviews.png" alt="" class="img-responsive img-circle"></div>
                </div>
            </div>
        </div>
    </a>
</div>